### ISSUE TITLE
a train error 

### ISSUE THREAD

**Issue by hujiaodou96** [YHJRUBY/ReID_baseline#2]
when I run train.py ,it occurs the error below:

Traceback (most recent call last):
  File "train.py", line 179, in <module>
    ], momentum=0.9, weight_decay=5e-4, nesterov=True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pytorch\lib\site-packages\torch\optim\sgd.py", line 53, in __init__
    if not 0.0 <= lr:
TypeError: unorderable types: float() <= object()

I want to know how to solve this problem, thx

**Comment by ye-hongjiang** [comment]
@hujiaodou96 It's a strange problem. What's your pytorch version?

**Comment by hujiaodou96** [comment]
Python 3.6.2 :: Anaconda custom (64-bit)

**Comment by hujiaodou96** [comment]
torch : 0.4.0a0+16b0adb

**Comment by ye-hongjiang** [comment]
My test environment is '0.3.1.post2', but I don't think it makes some differences. Did you change any codes? Did you try to replace the `arg.learning_rate` variable to `0.1` or other constants?

**Comment by hujiaodou96** [comment]
no ,is this code effective in windows pytorch?

**Comment by ye-hongjiang** [comment]
I tested in macOS 10.13.3. You can try to replace the `arg.learning_rate` variable to constants, according to the error occurred.

**Comment by ye-hongjiang** [comment]
Have you solved the problem? If not, please inform me. Closed.
