### ISSUE TITLE
test error load model

### ISSUE THREAD

**Issue by yja1** [YHJRUBY/ReID_baseline#3]
TypeError: 'str' object is not callable

error line: test.py
state_dict = torch.load(save_path, map_location='cpu')

**Comment by ye-hongjiang** [comment]
It's hard to figure out where is the problem. Can you apply more details, like the error traceback, any changes from the code or your environment.

**Comment by yja1** [comment]
state_dict = torch.load(save_path) #use this is OK

**Comment by yja1** [comment]
in line utils.py load_network()

**Comment by ye-hongjiang** [comment]
Did you test on CPU? What's your pytorch version (`torch.__version__`)?

Try to replace `utils.py` line 38 `state_dict = torch.load(save_path, map_location='cpu')` with:
`state_dict = torch.load(save_path, map_location=lambda storage, loc: storage)`

**Comment by yja1** [comment]
thx.
state_dict = torch.load(save_path, map_location=lambda storage, loc: storage) 
and state_dict = torch.load(save_path) is ok
