### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by HAONVSHI** [YHJRUBY/ReID_baseline#6]
the error is:
AttributeError:'DataParallel' object has no attribute 'set_return_features'

I don't know how to correct it

**Comment by bigAndSmall** [comment]
#needs to add
if isinstance(model,torch.nn.DataParallel):
		model = model.module
I found the solution from this website: https://blog.csdn.net/weixin_41990278/article/details/105127101,  and i solve it.
